# Load .env file secara otomatis di awal
spring.config.import=optional:file:.env[.properties]

spring.application.name=order_service

# Konfigurasi JPA / Hibernate (Aman dilihat publik di GitHub)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true